site_name: Simplifying SQLAlchemy
repo_url: https://github.com/Arcader717/SAlc_Simplified
repo_name: Simplifying SQLAlchemy
site_author: Arcader717
lang: en
nav:
  - Home: index.md
  - Quickstart: introduction/quickstart.md
theme: readthedocs
